name: Continous Integration and Deployment

on:
  push:
      branches:
              master
jobs:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup .Net 5
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'
      -
        name: Restore dependancies
        run: dotnet restore
      -
        name: Build app
        run: dotnet build -c Release --no-restore
        